/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/
#pragma once

#include <memory>
#include "JuceHeader.h"
#include "gui/CommandTarget.h"
#include "gui/Style.h"


namespace e3 {

    class Processor;
    class TabComponent;
    class EditorPanel;
    class BrowserPanel;
    class SetupPanel;
    class Monitor;


    class AudioEditor : public AudioProcessorEditor, public CommandTarget
    {
    public:
        AudioEditor(Processor*);
        ~AudioEditor();

        void paint(Graphics&) override;
        void resized() override;
        void createIcon(Image& image);

        bool perform(const InvocationInfo& info) override;      // Implementation for ApplicationCommandTarget

        ScopedPointer<Style> style_;

    private:
        void restoreWindowState();
        void createComponents();
        void openBank(File file);

        void onOpenBank();
        void onSaveBank(bool askForFilename);
        void onNewBank();
        void onLoadInstrument();

        enum PanelIds {
            kEditorPanel = 0,
            kBrowserPanel = 1,
            kSetupPanel = 2
        };

        Processor* processor_;

        ScopedPointer<TabComponent> tabPanel_;
        ScopedPointer<EditorPanel>  editorPanel_;
        ScopedPointer<BrowserPanel> browserPanel_;
        ScopedPointer<SetupPanel> setupPanel_;
        ScopedPointer<Monitor> monitor_;
        ScopedPointer<ResizableCornerComponent> resizer_;

        ComponentBoundsConstrainer resizeLimits_;

        JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(AudioEditor)
    };

} // namespace e3